print("Trostel Gábor")
print("2020.09.03")
print("        __")
print("      _ ||")
print("     / \||")
print("    /   \|")
print("   /     \ ")
print("   |     | ")
print("   |     | ")
print("   ------- ")
