print("Gábor")
print("2020.09.03.")
print("      __")
print("      ||")
print("      || /|")
print("      ||/ |")
print("      |/  |")
print("      /   |")
print("     /    |")
print("     |    |")
print("     |    |")
print("     ------")
